----INSERT QUERY----------
SELECT NVL(MAX(TO_NUMBER(CODE)),0) FROM NOTICE 
SELECT *FROM NOTICE;

--GET LIST

SELECT *
FROM(
  SELECT ROWNUM NUM ,N.*
  FROM (
    SELECT *
    FROM 
    	NOTICE_VIEW 
  	WHERE TITLE LIKE '%%'
    ORDER BY N.REGDATE DESC
  )N
)
  WHERE NUM BETWEEN 11 AND 20

SELECT MAX(TO_NUMBER(CODE)) FROM NOTICE 

--���Ȳ
SELECT N.CODE,N.TITLE,N.WRITER,N.CONTENT,N.REGDATE,N.HIT,COUNT(C.CODE) CMTCNT
FROM
	NOTICE N LEFT OUTER JOIN "COMMENT" C
	ON N.CODE = C.NOTICE_CODE
	GROUP BY N.CODE,N.TITLE,N.WRITER,N.CONTENT,N.REGDATE,N.HIT
	
	

--(
--	SELECT N.CODE, N.TITLE, N.WRITER, N.CONTENT, N.REGDATE, N.HIT, M.NAME WRITER_NAME, COUNT(C.CODE) CMT_CNT 
--	FROM
--		MEMBER M
--		RIGHT OUTER JOIN NOTICE N ON M.MID = N.WRITER
--		LEFT OUTER JOIN "COMMENT" C ON N.CODE = C.NOTICE_CODE
--	GROUP BY N.CODE, N.TITLE, N.WRITER, N.CONTENT, N.REGDATE, N.HIT, M.NAME
--	ORDER BY N.REGDATE DESC
--) N
	

